// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO3LyFILBWBXmu4hXeeWmbxKeWPxkbrZM',
    appId: '1:285239876704:web:4db39b01d56eca46edf705',
    messagingSenderId: '285239876704',
    projectId: 'moughitapp-b7714',
    authDomain: 'moughitapp-b7714.firebaseapp.com',
    storageBucket: 'moughitapp-b7714.firebasestorage.app',
    measurementId: 'G-DLK0B0ZNZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl0h0GtP0TAwHHyCmIgWmipKNWC_qpnao',
    appId: '1:285239876704:android:c715e2c5a8f2ebf2edf705',
    messagingSenderId: '285239876704',
    projectId: 'moughitapp-b7714',
    storageBucket: 'moughitapp-b7714.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChdaJq2WX6hcZF5TMZXzg4f-gDGRR8MPo',
    appId: '1:285239876704:ios:c348bf6fee3495ddedf705',
    messagingSenderId: '285239876704',
    projectId: 'moughitapp-b7714',
    storageBucket: 'moughitapp-b7714.firebasestorage.app',
    iosBundleId: 'com.moughit.moughitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChdaJq2WX6hcZF5TMZXzg4f-gDGRR8MPo',
    appId: '1:285239876704:ios:c348bf6fee3495ddedf705',
    messagingSenderId: '285239876704',
    projectId: 'moughitapp-b7714',
    storageBucket: 'moughitapp-b7714.firebasestorage.app',
    iosBundleId: 'com.moughit.moughitApp',
  );
}
